### ISSUE TITLE
Consistency of aws-parallelcluster and aws-java-sdk-cloudformation 

### ISSUE THREAD

**Issue by SunPj** [awsdocs/aws-parallelcluster-user-guide#40]
We are using cfncluster-1.6.1 on our project via java SDK and thinking about updating cfncluster version. In accordance with documentation it was renamed to aws-parallelcluster. 

Could you tell me whether we can still use aws-java-sdk-cloudformation or is there any other Java SDK for parallelcluster? 

Thanks

**Comment by HLeeHart** [comment]
AWS ParallelCluster does not have a specific Java SDK. For AWS CloudFormation (and other AWS services), there are two Java SDKs - https://github.com/aws/aws-sdk-java and https://github.com/aws/aws-sdk-java-v2. Since you referred to "aws-java-sdk-cloudformation", I think you may be using Maven. If so, https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/setup-project-maven.html has directions on using Maven with the V2 version of the AWS SDK for Java.

Thanks

**Comment by SunPj** [comment]
Thanks @HLeeHart 

Does that mean that I can't create/manage/remove AWS ParallelCluster from my Java code or Is it feasible just using general AWS Java SDK? 

Thanks

**Comment by lukeseawalker** [comment]
Hi @SunPj,
I'm not sure how you are integrating CfnCluster with your Java project, but if you were calling cfncluster CLI via java SDK you can call the ParallelCluster CLI with the same commands as before.

L

**Comment by SunPj** [comment]
Hi @lukeseawalker 

For example we have something like this 
https://github.com/aws/aws-sdk-java/blob/master/src/samples/AwsCloudFormation/CloudFormationSample.java

We are creating/shutdown CFN cluster via JAVA API. How about parallelcluster, can we work with it in the same way?

**Comment by lukeseawalker** [comment]
As I am understanding, you were calling directly the CfnCluster cloudformation template to create the cluster, so it should just be a matter of using the ParallelCluster cloudformation template instead.
